exports.seed = (knex) => {
  // Deletes ALL existing entries
  return knex('recipes')
    .del()
    .then(() => {
      // Inserts seed entries
      return knex('recipes').insert([
        {
          id: '1',
          title: 'Spicy Chicken and Pepper Jack Pizza',
          servings: 4,
          cooking_time: '45min',
          publisher: 'My Baking Addiction',
          summary:
            'Spicy Chicken and Pepper Jack pizza made with Sargento Pepper Jack cheese is the perfect flatbread pizza for game night',
          image_url: '/images/spicy chicken and pepperjack pizza.png',
          ingredients: JSON.stringify([
            '1tsp. canola or olive oil',
            '1/2 cup chopped sweet onion',
            '3 cups diced fresh red yellow and green bell peppers',
            '1 pizza base',
            '1/2 cup salsa',
            '2 cups sargento chefstyle shredded pepper jack cheese',
            'chopped cilantro or dried oregano to top',
          ]),
          method: JSON.stringify([
            `Heat oil in a large skillet over medium heat. Add onion; sauté 2 minutes. Add bell peppers; sauté 5 minutes or until crisp-tender.`,
            `Meanwhile, unroll pizza dough onto a 15 x 10-inch jelly roll pan coated with cooking spray; press dough evenly to all edges of pan. Bake in preheated 425°F 8 minutes. 3. Stir salsa into cooked vegetables; spread over partially baked crust. Top with chicken and cheese.`,
            `Bake 10 to 12 minutes or until crust is deep golden brown. Cut into squares; garnish with cilantro or oregano if desired.`,
          ]),
          weeks_dinners: 'true',
          favourited: 'false',
        },
        {
          id: '2',
          title: 'Chicken Congee',
          servings: 4,
          cooking_time: '60min',
          publisher: 'Made with Lau',
          summary:
            'Check out this easy Chinese Chicken Congee by Daddy Lau, a Chinese chef with over 50 years of experience. This soup is delicious, easy and great for cold nights',
          image_url: '/images/congee.png',
          ingredients: JSON.stringify([
            '1 rice cup white rice (a "rice cup" is about 3/4 of a standard US cup. Jasmine rice is preferred but any white rice will work!)',
            '340 g chicken (use any amount you want)',
            '8 cups of water',
            '14.2 g ginger',
            '2 pieces green onion',
            'cilantro (to taste)',
            'Chicken marinade',
            `2 tsp cornstarch`,
            `1 tbsp oyster sauce `,
            `2 tbsp water`,
            `0.50 tsp chicken bouillon`,
            `2 tbsp vegetable oil`,
          ]),
          method: JSON.stringify([
            `Wash rice (1 rice cup) in a bowl:`,
            `Start boiling water (8 cup). Chop ginger (14.2 g) into thin slices, and then into thin strips. Chop a few strands of cilantro and green onion (2 pieces) into small pieces.`,
            `Cut the chicken (340 g) into thin slices and place it in a bowl to marinate. Add oyster sauce (1 tbsp), cornstarch (2 tsp), chicken bouillon (0.50 tsp), and water (2 tbsp). Mix and massage the chicken and the marinade together for 30 seconds until there's no liquid left. Then, add vegetable oil (2 tbsp) to the bowl and mix it around with chopsticks for another 20-30 seconds. The cornstarch helps glue the flavors to the chicken, and helps lock the juices inside the chicken. The oil helps prevent the chicken from clumping together, and also helps seal the juices inside the chicken as well.`,
            `Pour the boiled water (8 cup) from earlier into a pot, set on high heat, and wait for the pot to boil before adding our rice. It's important not to add the rice before the pot starts boiling. Once the pot (water only) is boiling, add the rice and stir it around a bit. Another important tip - don't stir the rice once the pot is boiling yet again, otherwise it will be more likely to stick to the bottom of the pot. cover and wait till it boils again. Once the pot is boiling again, we'll partially cover the pot and let it cook at medium heat for 25 minutes.`,
            `Once we've hit 25 minutes, we can either proceed with this step or cook it for longer. If you're happy with where your rice is at, start whisking the pot rapidly and constantly for 2-3 minutes. This helps speed up our cooking time, and helps break down the rice into smaller, fluffier pieces.`,
            `Set the stove to high heat, and slowly add the chicken over the course of 30 to 60 seconds, stirring constantly as you go. If you add it all at once, it will clump up. Stir the chicken around for another 1-2 minutes. Once the pot is boiling again, it should be ready. We can also judge by looking at the chicken to make sure there are no raw spots left. `,
            `Almost there! Add the strips of ginger, as well as salt (1 tsp) and chicken bouillon (1 tsp). Stir everything around for 20-30 seconds.`,
            `Turn off the heat, and pour the jook into your favorite bowl. Garnish with the green onions and cilantro.`,
          ]),
          weeks_dinners: 'true',
          favourited: 'false',
        },
        {
          id: '3',
          title: 'Spicy Chicken and Pepper Jack Pizza',
          servings: 4,
          cooking_time: '45min',
          publisher: 'My Baking Addiction',
          summary:
            'Spicy Chicken and Pepper Jack pizza made with Sargento Pepper Jack cheese is the perfect flatbread pizza for game night',
          image_url: '/images/spicy chicken and pepperjack pizza.png',
          ingredients: JSON.stringify([
            '1tsp. canola or olive oil',
            '1/2 cup chopped sweet onion',
            '3 cups diced fresh red yellow and green bell peppers',
            '1 pizza base',
            '1/2 cup salsa',
            '2 cups sargento chefstyle shredded pepper jack cheese',
            'chopped cilantro or dried oregano to top',
          ]),
          method: JSON.stringify([
            `Heat oil in a large skillet over medium heat. Add onion; sauté 2 minutes. Add bell peppers; sauté 5 minutes or until crisp-tender.`,
            `Meanwhile, unroll pizza dough onto a 15 x 10-inch jelly roll pan coated with cooking spray; press dough evenly to all edges of pan. Bake in preheated 425°F 8 minutes. 3. Stir salsa into cooked vegetables; spread over partially baked crust. Top with chicken and cheese.`,
            `Bake 10 to 12 minutes or until crust is deep golden brown. Cut into squares; garnish with cilantro or oregano if desired.`,
          ]),
          weeks_dinners: 'false',
          favourited: 'false',
        },
        {
          id: '4',
          title: 'Spicy Chicken and Pepper Jack Pizza',
          servings: 4,
          cooking_time: '45min',
          publisher: 'My Baking Addiction',
          summary:
            'Spicy Chicken and Pepper Jack pizza made with Sargento Pepper Jack cheese is the perfect flatbread pizza for game night',
          image_url: '/images/spicy chicken and pepperjack pizza.png',
          ingredients: JSON.stringify([
            '1tsp. canola or olive oil',
            '1/2 cup chopped sweet onion',
            '3 cups diced fresh red yellow and green bell peppers',
            '1 pizza base',
            '1/2 cup salsa',
            '2 cups sargento chefstyle shredded pepper jack cheese',
            'chopped cilantro or dried oregano to top',
          ]),
          method: JSON.stringify([
            `Heat oil in a large skillet over medium heat. Add onion; sauté 2 minutes. Add bell peppers; sauté 5 minutes or until crisp-tender.`,
            `Meanwhile, unroll pizza dough onto a 15 x 10-inch jelly roll pan coated with cooking spray; press dough evenly to all edges of pan. Bake in preheated 425°F 8 minutes. 3. Stir salsa into cooked vegetables; spread over partially baked crust. Top with chicken and cheese.`,
            `Bake 10 to 12 minutes or until crust is deep golden brown. Cut into squares; garnish with cilantro or oregano if desired.`,
          ]),
          weeks_dinners: 'true',
          favourited: 'false',
        },
        {
          id: '5',
          title: 'Spicy Chicken and Pepper Jack Pizza',
          servings: 4,
          cooking_time: '45min',
          publisher: 'My Baking Addiction',
          summary:
            'Spicy Chicken and Pepper Jack pizza made with Sargento Pepper Jack cheese is the perfect flatbread pizza for game night',
          image_url: '/images/spicy chicken and pepperjack pizza.png',
          ingredients: JSON.stringify([
            '1tsp. canola or olive oil',
            '1/2 cup chopped sweet onion',
            '3 cups diced fresh red yellow and green bell peppers',
            '1 pizza base',
            '1/2 cup salsa',
            '2 cups sargento chefstyle shredded pepper jack cheese',
            'chopped cilantro or dried oregano to top',
          ]),
          method: JSON.stringify([
            `Heat oil in a large skillet over medium heat. Add onion; sauté 2 minutes. Add bell peppers; sauté 5 minutes or until crisp-tender.`,
            `Meanwhile, unroll pizza dough onto a 15 x 10-inch jelly roll pan coated with cooking spray; press dough evenly to all edges of pan. Bake in preheated 425°F 8 minutes. 3. Stir salsa into cooked vegetables; spread over partially baked crust. Top with chicken and cheese.`,
            `Bake 10 to 12 minutes or until crust is deep golden brown. Cut into squares; garnish with cilantro or oregano if desired.`,
          ]),
          weeks_dinners: 'false',
          favourited: 'false',
        },
        {
          id: '6',
          title: 'Spicy Chicken and Pepper Jack Pizza',
          servings: 4,
          cooking_time: '45min',
          publisher: 'My Baking Addiction',
          summary:
            'Spicy Chicken and Pepper Jack pizza made with Sargento Pepper Jack cheese is the perfect flatbread pizza for game night',
          image_url: '/images/spicy chicken and pepperjack pizza.png',
          ingredients: JSON.stringify([
            '1tsp. canola or olive oil',
            '1/2 cup chopped sweet onion',
            '3 cups diced fresh red yellow and green bell peppers',
            '1 pizza base',
            '1/2 cup salsa',
            '2 cups sargento chefstyle shredded pepper jack cheese',
            'chopped cilantro or dried oregano to top',
          ]),
          method: JSON.stringify([
            `Heat oil in a large skillet over medium heat. Add onion; sauté 2 minutes. Add bell peppers; sauté 5 minutes or until crisp-tender.`,
            `Meanwhile, unroll pizza dough onto a 15 x 10-inch jelly roll pan coated with cooking spray; press dough evenly to all edges of pan. Bake in preheated 425°F 8 minutes. 3. Stir salsa into cooked vegetables; spread over partially baked crust. Top with chicken and cheese.`,
            `Bake 10 to 12 minutes or until crust is deep golden brown. Cut into squares; garnish with cilantro or oregano if desired.`,
          ]),
          weeks_dinners: 'false',
          favourited: 'false',
        },
        {
          id: '7',
          title: 'Spicy Chicken and Pepper Jack Pizza',
          servings: 4,
          cooking_time: '45min',
          publisher: 'My Baking Addiction',
          summary:
            'Spicy Chicken and Pepper Jack pizza made with Sargento Pepper Jack cheese is the perfect flatbread pizza for game night',
          image_url: '/images/spicy chicken and pepperjack pizza.png',
          ingredients: JSON.stringify([
            '1tsp. canola or olive oil',
            '1/2 cup chopped sweet onion',
            '3 cups diced fresh red yellow and green bell peppers',
            '1 pizza base',
            '1/2 cup salsa',
            '2 cups sargento chefstyle shredded pepper jack cheese',
            'chopped cilantro or dried oregano to top',
          ]),
          method: JSON.stringify([
            `Heat oil in a large skillet over medium heat. Add onion; sauté 2 minutes. Add bell peppers; sauté 5 minutes or until crisp-tender.`,
            `Meanwhile, unroll pizza dough onto a 15 x 10-inch jelly roll pan coated with cooking spray; press dough evenly to all edges of pan. Bake in preheated 425°F 8 minutes. 3. Stir salsa into cooked vegetables; spread over partially baked crust. Top with chicken and cheese.`,
            `Bake 10 to 12 minutes or until crust is deep golden brown. Cut into squares; garnish with cilantro or oregano if desired.`,
          ]),
          weeks_dinners: 'false',
          favourited: 'false',
        },
        {
          id: '8',
          title: 'Spicy Chicken and Pepper Jack Pizza',
          servings: 4,
          cooking_time: '45min',
          publisher: 'My Baking Addiction',
          summary:
            'Spicy Chicken and Pepper Jack pizza made with Sargento Pepper Jack cheese is the perfect flatbread pizza for game night',
          image_url: '/images/spicy chicken and pepperjack pizza.png',
          ingredients: JSON.stringify([
            '1tsp. canola or olive oil',
            '1/2 cup chopped sweet onion',
            '3 cups diced fresh red yellow and green bell peppers',
            '1 pizza base',
            '1/2 cup salsa',
            '2 cups sargento chefstyle shredded pepper jack cheese',
            'chopped cilantro or dried oregano to top',
          ]),
          method: JSON.stringify([
            `Heat oil in a large skillet over medium heat. Add onion; sauté 2 minutes. Add bell peppers; sauté 5 minutes or until crisp-tender.`,
            `Meanwhile, unroll pizza dough onto a 15 x 10-inch jelly roll pan coated with cooking spray; press dough evenly to all edges of pan. Bake in preheated 425°F 8 minutes. 3. Stir salsa into cooked vegetables; spread over partially baked crust. Top with chicken and cheese.`,
            `Bake 10 to 12 minutes or until crust is deep golden brown. Cut into squares; garnish with cilantro or oregano if desired.`,
          ]),
          weeks_dinners: 'false',
          favourited: 'false',
        },
        {
          id: '9',
          title: 'Spicy Chicken and Pepper Jack Pizza',
          servings: 4,
          cooking_time: '45min',
          publisher: 'My Baking Addiction',
          summary:
            'Spicy Chicken and Pepper Jack pizza made with Sargento Pepper Jack cheese is the perfect flatbread pizza for game night',
          image_url: '/images/spicy chicken and pepperjack pizza.png',
          ingredients: JSON.stringify([
            '1tsp. canola or olive oil',
            '1/2 cup chopped sweet onion',
            '3 cups diced fresh red yellow and green bell peppers',
            '1 pizza base',
            '1/2 cup salsa',
            '2 cups sargento chefstyle shredded pepper jack cheese',
            'chopped cilantro or dried oregano to top',
          ]),
          method: JSON.stringify([
            `Heat oil in a large skillet over medium heat. Add onion; sauté 2 minutes. Add bell peppers; sauté 5 minutes or until crisp-tender.`,
            `Meanwhile, unroll pizza dough onto a 15 x 10-inch jelly roll pan coated with cooking spray; press dough evenly to all edges of pan. Bake in preheated 425°F 8 minutes. 3. Stir salsa into cooked vegetables; spread over partially baked crust. Top with chicken and cheese.`,
            `Bake 10 to 12 minutes or until crust is deep golden brown. Cut into squares; garnish with cilantro or oregano if desired.`,
          ]),
          weeks_dinners: 'false',
          favourited: 'false',
        },
      ])
    })
}
